### ISSUE TITLE
You are missing an 'event' from one of your rules

### ISSUE THREAD

**Issue by alexkalderimis** [radekstepan/grunt-sandbox-css#10]
Specifically this one: https://github.com/radekstepan/grunt-sandbox-css/blob/master/tasks/lib.coffee#L93-L95

```coffee
    parser.addListener 'startfontface', ->
      nlIfNeeded event
      output.push "@fontface {"
```

This causes the lib to die with a really unhelpful message ('event is not defined').

I will try and submit a patch ASAP

(also, Hello there!)

**Comment by alexkalderimis** [comment]
Also, as you will be aware, the string pushed onto the output was incorrect - I fixed that too.

**Comment by radekstepan** [comment]
Thanks for that Alex, will bump version and push to npm.

**Comment by radekstepan** [comment]
Thanks for that Alex, will bump version and push to npm.

**Comment by radekstepan** [comment]
Ok bumped to `5.0.1`

**Comment by alexkalderimis** [comment]
Sweet, thanks.
